channels:
- conda-forge
dependencies:
- python=3.10.19
- pip<=25.3
- pip:
  - mlflow==2.19.0
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==7.1.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
  - xgboost==3.1.2
name: mlflow-env
